name = "obicei"
main = "./worker/index.ts"
compatibility_date = "2025-04-03"
compatibility_flags = ["nodejs_compat"]

[assets]
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[vars]
VAPID_SUBJECT = "mailto:noreply@obicei.app"

[[d1_databases]]
binding = "DB"
database_name = "obicei"
database_id = "45601855-2c99-4443-9b6c-c1000850fba2"

[triggers]
crons = ["* * * * *"]
